name: CI-CD

on:
  pull_request:
    branches: ["master", "dev"]
    types: [opened, synchronize]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  StaticAnalysis:
    uses: ./.github/workflows/call-static-analysis.yml
    secrets:
      GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}

  AutoMerge:
    needs: StaticAnalysis
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: success()
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
